### ISSUE TITLE
Update README: Unknown import Json.Schema

### ISSUE THREAD

**Issue by piu130** [niho/json-schema-form#1]
The `Example usage` in the README does not work. Elm does not find the module `Json.Schema` used with `Json.Schema.fromString schema` in `init` function.

Could you fix that? Do I need to install another module? Or was the function `fromString` renamed?

**Comment by niho** [comment]
You need to install the `json-tools/json-schema` dependency which is used to parse the schema. See the example project in the `examples/` folder for a working `elm.json` file.

I will add a note about the dependency requirement to the README. Thank you for making me aware of the problem!
